module.exports = {
  apps: [
    {
      name: 'elementx-backend',
      script: 'uvicorn',
      args: 'main:app --host 0.0.0.0 --port 8000',
      interpreter: 'python3',
      cwd: '/Users/nish/ElementX/backend',
      env: {
        MONGODB_URI: process.env.MONGODB_URI || 'mongodb://localhost:27017/elementx',
        JWT_SECRET: process.env.JWT_SECRET || 'superlongrandomkey1234567890',
      },
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '1G',
      error_file: './logs/backend-error.log',
      out_file: './logs/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'elementx-frontend',
      script: 'npm',
      args: 'start',
      cwd: '/Users/nish/ElementX/frontend',
      env: {
        REACT_APP_API_URL: process.env.REACT_APP_API_URL || 'http://localhost:8000',
        PORT: 3000,
      },
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: './logs/frontend-error.log',
      out_file: './logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
  ],
};
