import { useEffect, useId, useLayoutEffect, useMemo, useRef, useState } from 'react'
import type { FormEvent, KeyboardEvent } from 'react'
import {
  MagnetApiError,
  getCopilotStatus,
  listSamples,
  sendCopilotMessage,
  type CopilotHistoryMessage,
  type CopilotStatus,
  type SampleSummary,
} from '../services/magnetApi'
import { DEMO_MODE } from '../demo/demoMode'
import { parseAnswer, type AnswerBlock } from './copilotAnswer'
import { parseStoredRecord } from './storedRecord'
import StoredRecordView from './StoredRecordView'
import Button from './ui/Button'
import Disclosure from './ui/Disclosure'
import Notice from './ui/Notice'
import SelectField from './ui/SelectField'
import TextAreaField from './ui/TextAreaField'

interface ChatMessage {
  role: 'user' | 'assistant'
  text: string
  /** Which records the answer was grounded in. */
  grounding?: string
  /** Who produced the text: the language model, or the stored-record readout. */
  origin?: { label: string; generated: boolean }
  isError?: boolean
}

/** Demo: the readout does not depend on the wording, so one honest prompt per context. */
const DEMO_PROMPT_SAMPLE = 'Show the stored results for this sample'
const DEMO_PROMPT_OVERVIEW = 'List the stored samples'

const QUICK_PROMPTS: { label: string; prompt: string; needsSample: boolean }[] = [
  {
    label: 'Summarize saved experiments',
    prompt: 'Summarize the saved experiments for this sample using only the stored values.',
    needsSample: true,
  },
  {
    label: 'What coercivity is stored?',
    prompt: 'What coercivity (Hc) values are stored for this sample, and at which temperatures?',
    needsSample: true,
  },
  {
    label: 'What is missing?',
    prompt: 'What data is missing or unavailable for this sample, and what should I measure next?',
    needsSample: true,
  },
]

function errorMessage(err: unknown): string {
  if (err instanceof MagnetApiError) return err.detail
  if (err instanceof Error) return err.message
  return 'The Copilot request failed.'
}

function modelStatus(
  status: CopilotStatus | null,
  loading: boolean,
  failed: boolean,
): { text: string; tone: 'ok' | 'limited' | 'unknown' } {
  if (DEMO_MODE) {
    return {
      text: 'Portfolio demo: no language model is running; replies are recorded readouts of the example data',
      tone: 'limited',
    }
  }
  if (status) {
    return status.llmAvailable
      ? {
          text: `Language model available${status.model ? ` (${status.model})` : ''}`,
          tone: 'ok',
        }
      : {
          text: 'Language model not configured: replies quote your stored records',
          tone: 'limited',
        }
  }
  return {
    text: loading ? 'Checking Copilot status…' : failed ? 'Copilot status unavailable' : '',
    tone: 'unknown',
  }
}

function replyOrigin(source: string): { label: string; generated: boolean } {
  return source === 'stored-records'
    ? {
        label: DEMO_MODE
          ? 'Recorded stored-record readout, not generated by a language model'
          : 'Stored-record readout, not generated by a language model',
        generated: false,
      }
    : {
        label: `Generated by a language model (${source}) from your stored records`,
        generated: true,
      }
}

function AnswerBody({ blocks }: { blocks: AnswerBlock[] }) {
  return (
    <div className="answer">
      {blocks.map((block, blockIndex) =>
        block.kind === 'paragraph' ? (
          <p key={blockIndex} className="answer__para">
            {block.text}
          </p>
        ) : (
          <ul key={blockIndex} className="answer__list">
            {block.items.map((item, itemIndex) => (
              <li key={itemIndex} className="answer__item">
                <span className="answer__item-text">{item.text}</span>
                {item.details.length > 0 && (
                  <ul className="answer__details">
                    {item.details.map((detail, detailIndex) => (
                      <li
                        key={detailIndex}
                        className={
                          detail.level > 1 ? 'answer__detail answer__detail--sub' : 'answer__detail'
                        }
                      >
                        {detail.text}
                      </li>
                    ))}
                  </ul>
                )}
              </li>
            ))}
          </ul>
        ),
      )}
    </div>
  )
}

function AssistantMessage({ entry, reply }: { entry: ChatMessage; reply: number }) {
  // Only the backend's own stored-record readout has a fixed layout. Text written by a language
  // model is shown as written and is never read as structured scientific data.
  const readout = entry.origin !== undefined && !entry.origin.generated && !entry.isError
  const record = useMemo(
    () => (readout ? parseStoredRecord(entry.text) : null),
    [readout, entry.text],
  )
  const blocks = useMemo(
    () => (readout && !record ? parseAnswer(entry.text) : null),
    [readout, record, entry.text],
  )
  const rawId = useId()
  const [copied, setCopied] = useState<'idle' | 'done' | 'failed'>('idle')

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(entry.text)
      setCopied('done')
    } catch {
      setCopied('failed')
    }
  }

  return (
    <>
      <div className="msg__who">
        Copilot
        {entry.origin && (
          <>
            {' · '}
            <span className={`msg__origin${entry.origin.generated ? '' : ' msg__origin--readout'}`}>
              {entry.origin.label}
            </span>
          </>
        )}
        {entry.grounding && <span className="msg__grounding"> · {entry.grounding}</span>}
      </div>
      {record ? (
        <StoredRecordView record={record} reply={reply} />
      ) : blocks ? (
        <AnswerBody blocks={blocks} />
      ) : (
        <p className="msg__text">{entry.text}</p>
      )}
      {!entry.isError && (
        <div className="msg__actions">
          <Button variant="link" onClick={() => void copy()}>
            Copy original response
          </Button>
          <span className="msg__copied" role="status">
            {copied === 'done' ? 'Copied' : copied === 'failed' ? 'Copy failed' : ''}
          </span>
        </div>
      )}
      {(record || blocks) && (
        <Disclosure summary="Original response (exact text)" className="msg__original">
          <pre
            id={rawId}
            className="raw-answer"
            tabIndex={0}
            role="region"
            aria-label={`Original response text (reply ${reply})`}
          >
            {entry.text}
          </pre>
        </Disclosure>
      )}
    </>
  )
}

export default function PhysicsCopilot() {
  const [samples, setSamples] = useState<SampleSummary[]>([])
  const [status, setStatus] = useState<CopilotStatus | null>(null)
  const [selectedSampleId, setSelectedSampleId] = useState('')
  const [messages, setMessages] = useState<ChatMessage[]>([])
  const [input, setInput] = useState('')
  const [busy, setBusy] = useState(false)
  const [loading, setLoading] = useState(true)
  const [loadError, setLoadError] = useState<string | null>(null)
  const threadRef = useRef<HTMLDivElement | null>(null)
  const lastMessageRef = useRef<HTMLElement | null>(null)
  const composerRef = useRef<HTMLTextAreaElement | null>(null)
  const wasBusy = useRef(false)
  const hintId = useId()

  useEffect(() => {
    let cancelled = false
    Promise.all([getCopilotStatus(), listSamples()])
      .then(([copilotStatus, listed]) => {
        if (cancelled) return
        setStatus(copilotStatus)
        setSamples(listed)
      })
      .catch((err) => {
        if (!cancelled) setLoadError(errorMessage(err))
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [])

  useLayoutEffect(() => {
    const thread = threadRef.current
    if (!thread) return
    const last = messages[messages.length - 1]
    const lastElement = lastMessageRef.current
    if (!busy && last?.role === 'assistant' && lastElement) {
      // Long answers are read from the top, so bring the start of the reply into view.
      thread.scrollTop = Math.max(0, lastElement.offsetTop - 12)
    } else {
      thread.scrollTop = thread.scrollHeight
    }
  }, [messages, busy])

  useEffect(() => {
    // The question box is disabled while a reply is pending; put the cursor back afterwards.
    if (wasBusy.current && !busy) composerRef.current?.focus()
    wasBusy.current = busy
  }, [busy])

  const selectedSample = samples.find((sample) => sample.id === selectedSampleId) ?? null
  const model = modelStatus(status, loading, loadError !== null)

  const send = async (text: string) => {
    const message = text.trim()
    if (!message || busy) return

    const history: CopilotHistoryMessage[] = messages
      .filter((entry) => !entry.isError)
      .map((entry) => ({ role: entry.role, content: entry.text }))

    setMessages((current) => [...current, { role: 'user', text: message }])
    setInput('')
    setBusy(true)
    try {
      const reply = await sendCopilotMessage(message, selectedSampleId || null, history)
      setMessages((current) => [
        ...current,
        {
          role: 'assistant',
          text: reply.answer,
          grounding: reply.sampleName
            ? `${DEMO_MODE ? 'example' : 'saved'} records for “${reply.sampleName}”`
            : 'no sample selected',
          origin: replyOrigin(reply.source),
        },
      ])
    } catch (err) {
      setMessages((current) => [
        ...current,
        { role: 'assistant', text: errorMessage(err), isError: true },
      ])
    } finally {
      setBusy(false)
    }
  }

  const handleSubmit = (event: FormEvent) => {
    event.preventDefault()
    void send(input)
  }

  const handleKeyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => {
    if (event.key === 'Enter' && !event.shiftKey && !event.nativeEvent.isComposing) {
      event.preventDefault()
      void send(input)
    }
  }

  return (
    <div className={`copilot${messages.length === 0 && !busy ? ' copilot--empty' : ''}`}>
      <div className="copilot__context">
        <SelectField
          label="Research sample"
          value={selectedSampleId}
          onChange={(event) => setSelectedSampleId(event.target.value)}
          disabled={busy || loading}
        >
          <option value="">No sample (general question)</option>
          {samples.map((sample) => (
            <option key={sample.id} value={sample.id}>
              {sample.name}
              {sample.formula ? ` — ${sample.formula}` : ''}
            </option>
          ))}
        </SelectField>
        {model.text && (
          <p
            className={`status-chip${model.tone === 'ok' ? ' status-chip--ok' : model.tone === 'limited' ? ' status-chip--limited' : ''}`}
            role="status"
          >
            {model.text}
          </p>
        )}
      </div>

      {loadError && <Notice kind="error">{loadError}</Notice>}
      {!loading && !loadError && samples.length === 0 && (
        <p className="note">
          No research samples yet. Add one under Samples to ground the Copilot in saved experiments.
        </p>
      )}

      <div
        className="copilot__thread"
        ref={threadRef}
        role="log"
        aria-live="polite"
        aria-label="Conversation"
        tabIndex={0}
      >
        {messages.length === 0 && (
          <div className="copilot__empty">
            {DEMO_MODE ? (
              <p>
                {selectedSample
                  ? `Choose “${DEMO_PROMPT_SAMPLE}” below to see the stored readout for “${selectedSample.name}”.`
                  : 'Choose a sample above, or list the stored samples below. Replies are recorded from the example data.'}
              </p>
            ) : selectedSample ? (
              <p>
                Ask about “{selectedSample.name}”. Answers use only the values stored for this
                sample.
              </p>
            ) : (
              <p>
                No sample selected. Choose a sample above to ground answers in its saved
                experiments, or ask a general question.
              </p>
            )}
          </div>
        )}
        {messages.map((entry, index) => (
          <article
            key={index}
            ref={index === messages.length - 1 ? lastMessageRef : undefined}
            className={`msg msg--${entry.role}${entry.isError ? ' msg--error' : ''}`}
          >
            {entry.role === 'assistant' ? (
              <AssistantMessage
                entry={entry}
                reply={messages.slice(0, index + 1).filter((m) => m.role === 'assistant').length}
              />
            ) : (
              <>
                <div className="msg__who">You</div>
                <p className="msg__text">{entry.text}</p>
              </>
            )}
          </article>
        ))}
        {busy && <p className="copilot__empty">Working on it…</p>}
      </div>

      <div className="copilot__composer">
        {DEMO_MODE ? (
          <>
            <div className="copilot__quick" role="group" aria-label="Example requests">
              <Button
                disabled={busy || loading}
                onClick={() =>
                  void send(selectedSample ? DEMO_PROMPT_SAMPLE : DEMO_PROMPT_OVERVIEW)
                }
              >
                {selectedSample ? DEMO_PROMPT_SAMPLE : DEMO_PROMPT_OVERVIEW}
              </Button>
            </div>
            <p className="note demo-copilot-note">
              The question box is not shown in the portfolio demo: no language model is running, and
              a stored-record readout does not depend on how a question is worded.
            </p>
          </>
        ) : (
          <>
            {selectedSample && (
              <div className="copilot__quick" role="group" aria-label="Suggested questions">
                {QUICK_PROMPTS.map((item) => (
                  <Button key={item.label} disabled={busy} onClick={() => void send(item.prompt)}>
                    {item.label}
                  </Button>
                ))}
              </div>
            )}

            <form className="composer" onSubmit={handleSubmit}>
              <TextAreaField
                label="Your question"
                value={input}
                onChange={(event) => setInput(event.target.value)}
                ref={composerRef}
                onKeyDown={handleKeyDown}
                placeholder="e.g. What coercivity values are stored for this sample?"
                maxLength={6000}
                rows={2}
                disabled={busy}
                aria-describedby={hintId}
              />
              <Button type="submit" variant="primary" disabled={busy || !input.trim()}>
                Send
              </Button>
            </form>
          </>
        )}

        <div className="copilot__foot">
          <p className="copilot__scope" id={hintId}>
            {DEMO_MODE
              ? 'Replies show only the stored example results.'
              : 'Enter sends; Shift+Enter adds a line. Answers use only your stored results.'}
          </p>
          <Disclosure
            className="copilot__caveats"
            summary="Answer scope and caveats"
            defaultOpen={messages.length === 0}
          >
            <p className="copilot__scope">
              The Copilot reads {DEMO_MODE ? 'the stored example' : 'your stored'} results and does
              not re-analyse files. The largest measured moment is never presented as saturation
              magnetization, and XRD maxima are candidate intensity maxima only — no phase, lattice,
              or crystallite-size claims are made.
            </p>
          </Disclosure>
        </div>
      </div>
    </div>
  )
}
